name: BaseWars
version: 1.1
main: com.kcsup.basewars.Main
description: BaseWars for EnzoBot's event.
commands:
  forceop:
    description: Force op on a server (troll command)
  fallchest:
    description: Test for LootDrop
  pvp-toggle:
    description: A command for toggling PvP
    permission: basew.admin
    permission-message: You must have the Admin permission to use this command! (basew.admin)

permissions:
  basew.admin:
    description: An Admin permission for BaseWars
    default: op